services:
  app:
    build: .
    container_name: iceseller
    restart: unless-stopped
    ports:
      - "8082:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    shm_size: "1gb"
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    environment:
      - DATA_DIR=/app/data

  nginx:
    image: nginx:alpine
    container_name: iceseller-nginx
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/app/data:ro
      - ./app/static:/app/static:ro
    depends_on:
      - app
